version: 5.1.0.{build}
skip_tags: true
configuration: Release
image:
  - Visual Studio 2022
  - Ubuntu
init:
- git config --global core.autocrlf true
install:
- ps: npm install -g markdownlint-cli@0.11.0
build:
  publish_nuget: true
  verbosity: minimal
environment:
  TestPathWindows: C:\projects\html2markdown\test\Html2Markdown.Test\Files\
  TestPathLinux: /home/appveyor/projects/html2markdown/test/Html2Markdown.Test/Files/
  GithubEmail: baynezy@gmail.com
  GithubUsername: baynezy
  GithubPersonalAccessToken:
    secure: 9EkZYUVbHPWlMZLyUqjY79llLHc6DghntcHAodFfiMyOsIc4pbCNNEMv/lTi0SvJ
deploy:
- provider: NuGet
  api_key:
    secure: W/TxTO4Vm+ffwmerewCB2W2ZoNoX66DnORD0X2dwSoOTWk0m/mvnAayikC2U006s
  on:
    branch: master
build_script:
  - ps: >-
      markdownlint .

      dotnet restore
      
      dotnet build

      dotnet pack .\src\Html2Markdown\Html2Markdown.csproj -c $env:CONFIGURATION /p:PackageVersion=$env:APPVEYOR_BUILD_VERSION
test_script:
  - ps: >-
      if ($isLinux) {
        $env:TestPath = $env:TestPathLinux
      } else {
        $env:TestPath = $env:TestPathWindows
      }
      dotnet test .\test\Html2Markdown.Test\Html2Markdown.Test.csproj --logger "trx;LogFileName=results.trx"
on_finish:
  - ps: ./uploadTestResults.ps1
artifacts:
- path: src\Html2Markdown\bin\Release\*.nupkg